### ISSUE TITLE
Feature Request: Image Scaling

### ISSUE THREAD

**Issue by Hotohori** [bryal/DXGI_capture_lib#1]
First, great lib, exactly what I was searching for.

Would be nice if you would be able to scale the Image on the GPU before you get it. I didn't need a 100% size shot, only a very small Version and  3840x2160 on a 4K Display is really big (31MB). Want to use it for my own Ambilight App over Adalight.

Tried to do it myself, but badly I never used C++ and so I failed totally after many hours reading and trying . :/ Even difficult for me to understand the Code at all. So far I understand you need to create a second texture in the size you want and render the first texture on it.

I hope you are still able to code in C++, saw that the most of your later Projects are in Rust.

**Comment by bryal** [comment]
First of all, I'm happy you like the project!

As you noticed, I only really use Rust nowadays, and I've actually rewritten this very library in Rust as [dxgcap-rs](https://github.com/bryal/dxgcap-rs). While not hugely different, it is a bit more polished, has a couple or more features, and is less buggy. Is there any particular reason you can't use library instead of this one? Also, if you only want a working ambilight app, and don't particularly want to write it yourself, I have already written such an application myself, [Helion](https://github.com/bryal/Helion).

If do want to use this project specifically, I could probably take a look at adding a GPU rescaling feature. However, I'm currently swamped in work, and I don't actually know much DirectX and GPU stuff (just enough to make this lib 😅), so it could be a while...

**Comment by Hotohori** [comment]
Can't build dxgcap-rs by my own, possible the Source is incompatibility with the newest Rust version? Get 47 Errors when it want to compile "dxgi-win".

What known Bugs are in the C++ lib?

I want to write my own App with a GUI and some more Features. Already started with it, but Capturing is not build in yet. If there is another way to use the Desktop Duplication API I will try it, but actually your DLL seams the best way for me.

**Comment by bryal** [comment]
Sorry for not responding and fixing at the time of your comment, but I've now updated dxgcap-rs to work without dxgi-win and with latest rust. You're probably not interested anymore, but wanted to at least provide some closure for this issue.
